#! /bin/bash
dellist=$(find /Users/kmills -type f -size +100M 2>&1 | grep -v find)
NF=$(echo $dellist | awk '{print NF}')
for (( i=1; i <= $NF; i++ ))
do
echo $dellist | awk -v temp=$i '{print $temp}'
ls -lh $(echo $dellist | awk -v temp=$i '{print $temp}') | awk '{print "Do you want to remove this file? (y/n). Size is " $5}'
read answer
if [ $answer == "y" ];
then
rm -rf $(echo $dellist | awk -v temp=$i '{print $temp}')
echo "you pressed y"
elif [ $answer == "n" ];
then
echo "you pressed n"
else
echo "press (y/n)"
i=$i-1;
continue
fi
done